### ISSUE TITLE
Any plans to update the Docker Image?

### ISSUE THREAD

**Issue by Basskrapfen** [Nouuu/Docker-Projeqtor#5]
Hi,

do you have any plans to update your Docker image to the latest Projeqtor version (V10.4.2)?
If it is only to update the Dockerfile I could try providing a small pull request.

Thanks and best regards,
Oliver

**Comment by Nouuu** [comment]
Hi, I've updated the version and fixed some bugs in the Dockerfile along the way.
There shouldn't be any regressions regarding the rest of the configuration (we're switching to PHP 8.2 starting from version 10.3.0). 

I need to find a solution to automatically keep the Docker image version up to date.

But apart from that, for future versions, feel free to submit a pull request if I forget to do it!

**Comment by Basskrapfen** [comment]
Thanks a lot for the fast update!
