### ISSUE TITLE
No volume for attachments

### ISSUE THREAD

**Issue by Basskrapfen** [Nouuu/Docker-Projeqtor#6]
Hi,
there is currently no mount point defined in the Dockerfile for the attachments folder but attachments are enabled. This could lead in lost data when Projeqtor stores this in a non-persisted place.
I did a workaround by binding /mnt/attachments to a dedicated volume via compose and set the patch via the "Global Parameters" in Projeqtor.

Do you think it makes sense to add this path as a volume? 

It would also be possible to merge /mnt/documents and /mnt/attachments to something like /mnt/storage with subfolders (e.g. /mnt/storage/documents, /mnt/storage/attachments), but this would require some migration.

Thanks

**Comment by Nouuu** [comment]
Did and update to create attachment volume in the last release :+1:
