### ISSUE TITLE
New Versions of Projeqtor

### ISSUE THREAD

**Issue by Basskrapfen** [Nouuu/Docker-Projeqtor#7]
Hi,

there is a new major version available of Projeqtor. Do you plan releasing a new version of your Dockerfile for the latest version?

I could also try to helping by pushing a pull request, but I'm not sure how your test process looks like. Are you starting it up locally and check manually or there some GitHub build pipeline?

Thanks a lot!

**Comment by Basskrapfen** [comment]
@Nouuu Hi Nouuu, have you seen my question? Thanks.

**Comment by DHS1001** [comment]
It would be great if Projeqtor docker can be upgraded to the latest available version.

**Comment by Basskrapfen** [comment]
@Nouuu Have you seen my message?

**Comment by Nouuu** [comment]
Hi, sorry for late answer

Currently building and pushing latests versions :)

**Comment by Nouuu** [comment]
To answer your question, version release is working with github action that is triggered by tags, corresponding on the projeqtor version

**Comment by Nouuu** [comment]
https://github.com/Nouuu/Docker-Projeqtor/blob/main/.github/workflows/label.yml
https://github.com/Nouuu/Docker-Projeqtor/blob/main/Dockerfile#L8

**Comment by Basskrapfen** [comment]
Thanks a lot for the update! Works like a charm.
